{{- if gt (int .Values.api.replicas) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "vortex.fullname" . }}-api
  labels:
    {{- include "vortex.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "vortex.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
---
{{- if gt (int .Values.app.replicas) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "vortex.fullname" . }}-app
  labels:
    {{- include "vortex.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "vortex.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
{{- end }}
---
{{- if gt (int .Values.worker.replicas) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "vortex.fullname" . }}-worker
  labels:
    {{- include "vortex.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "vortex.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
{{- end }}
