ingress:
  enabled: true
  className: nginx
  api:
    host: api.vortex.omni.dev
  app:
    host: vortex.omni.dev
  tls:
    - secretName: vortex-tls
      hosts: [api.vortex.omni.dev, vortex.omni.dev]

api:
  corsAllowedOrigins: "https://vortex.omni.dev"
  auth:
    baseUrl: "https://identity.omni.dev"

app:
  baseUrl: "https://vortex.omni.dev"
  auth:
    baseUrl: "https://identity.omni.dev"
